// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YaziciTakip.Data;

#nullable disable

namespace YaziciTakip.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910061916_FiyatMasterDetay")]
    partial class FiyatMasterDetay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("YaziciTakip.Models.Fiyat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TedarikciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TurId");

                    b.HasIndex("TedarikciId", "TurId")
                        .IsUnique();

                    b.ToTable("Fiyatlar");
                });

            modelBuilder.Entity("YaziciTakip.Models.FiyatDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiyatId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SayfaBasiFiyat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TurId");

                    b.HasIndex("FiyatId", "BaslangicTarihi");

                    b.ToTable("FiyatDetaylari");
                });

            modelBuilder.Entity("YaziciTakip.Models.Hakedis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("TedarikciAd")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TedarikciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Hakedisler");
                });

            modelBuilder.Entity("YaziciTakip.Models.HakedisLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CurrentCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HakedisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PreviousCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TurAd")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TurId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("HakedisId");

                    b.HasIndex("PrinterId");

                    b.ToTable("HakedisLines");
                });

            modelBuilder.Entity("YaziciTakip.Models.PrintReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "TimestampUtc");

                    b.ToTable("PrintReadings");
                });

            modelBuilder.Entity("YaziciTakip.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TedarikciId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex("TedarikciId");

                    b.HasIndex("TurId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("YaziciTakip.Models.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Not")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tedarikciler");
                });

            modelBuilder.Entity("YaziciTakip.Models.Tur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Turler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Siyah-Beyaz"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Renkli"
                        });
                });

            modelBuilder.Entity("YaziciTakip.Models.Fiyat", b =>
                {
                    b.HasOne("YaziciTakip.Models.Tedarikci", "Tedarikci")
                        .WithMany("Fiyatlar")
                        .HasForeignKey("TedarikciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaziciTakip.Models.Tur", "Tur")
                        .WithMany()
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tedarikci");

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("YaziciTakip.Models.FiyatDetay", b =>
                {
                    b.HasOne("YaziciTakip.Models.Fiyat", "Fiyat")
                        .WithMany("Detaylar")
                        .HasForeignKey("FiyatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaziciTakip.Models.Tur", "Tur")
                        .WithMany()
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fiyat");

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("YaziciTakip.Models.HakedisLine", b =>
                {
                    b.HasOne("YaziciTakip.Models.Hakedis", "Hakedis")
                        .WithMany("Lines")
                        .HasForeignKey("HakedisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hakedis");
                });

            modelBuilder.Entity("YaziciTakip.Models.PrintReading", b =>
                {
                    b.HasOne("YaziciTakip.Models.Printer", "Printer")
                        .WithMany("Readings")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("YaziciTakip.Models.Printer", b =>
                {
                    b.HasOne("YaziciTakip.Models.Tedarikci", "Tedarikci")
                        .WithMany("Printers")
                        .HasForeignKey("TedarikciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YaziciTakip.Models.Tur", "Tur")
                        .WithMany("Printers")
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tedarikci");

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("YaziciTakip.Models.Fiyat", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("YaziciTakip.Models.Hakedis", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("YaziciTakip.Models.Printer", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("YaziciTakip.Models.Tedarikci", b =>
                {
                    b.Navigation("Fiyatlar");

                    b.Navigation("Printers");
                });

            modelBuilder.Entity("YaziciTakip.Models.Tur", b =>
                {
                    b.Navigation("Printers");
                });
#pragma warning restore 612, 618
        }
    }
}
