// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YaziciTakip.Data;

#nullable disable

namespace YaziciTakip.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904090414_AddHakedis")]
    partial class AddHakedis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("YaziciTakip.Models.Hakedis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Hakedisler");
                });

            modelBuilder.Entity("YaziciTakip.Models.HakedisLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HakedisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PreviousCounter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HakedisId");

                    b.HasIndex("PrinterId");

                    b.ToTable("HakedisLines");
                });

            modelBuilder.Entity("YaziciTakip.Models.PrintReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "TimestampUtc");

                    b.ToTable("PrintReadings");
                });

            modelBuilder.Entity("YaziciTakip.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("YaziciTakip.Models.HakedisLine", b =>
                {
                    b.HasOne("YaziciTakip.Models.Hakedis", "Hakedis")
                        .WithMany("Lines")
                        .HasForeignKey("HakedisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hakedis");
                });

            modelBuilder.Entity("YaziciTakip.Models.PrintReading", b =>
                {
                    b.HasOne("YaziciTakip.Models.Printer", "Printer")
                        .WithMany("Readings")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("YaziciTakip.Models.Hakedis", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("YaziciTakip.Models.Printer", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
